---
title: "원내정당 유튜브"
format: 
  dashboard:
    logo: assets/yt_logo.webp
editor_options: 
  chunk_output_type: console
---


# 채널 

## 기본정보

```{r}
library(arrow)
library(reactable)
library(dplyr)
library(tidyr)
library(ggplot2)
library(forcats)  # For fct_reorder

channels_stat <- 
  read_feather("data/channel_stat.feather")

channels_stat |> 
  mutate(party_name = factor(party_name, 
     levels = c("민주당", "국민의힘", "조국혁신당", 
                "개혁신당", "진보당", "새로운미래",
                "기본소득당", "사회민주당"))) |>
  arrange(party_name) |>
  select(채널 = channel, 
         정당명 = party_name, 
         채널명 = channel_name, 
         개설일 = published_at, 
         설명 = channel_description,
         키워드 = channel_keywords,
         토픽범주 = topic_categories) |> 
  mutate(개설일 = as.Date(개설일)) |>
  reactable(
      searchable = TRUE,
      defaultColDef = colDef(
        header = function(value) gsub(".", " ", value, fixed = TRUE),
        align = "center",
        minWidth = 30,
        headerStyle = list(background = "#f7f7f8")
      ),
      columns = list(
        채널 = colDef(html = TRUE, cell = JS("
          function(cellInfo) {
            // Render as a link
            return '<a href=https://www.youtube.com//watch?v=' + cellInfo.value + '/>' + cellInfo.value + '</a>'
          }")),
        정당명   = colDef(show = TRUE, minWidth = 10),  
        채널명   = colDef(show = TRUE, minWidth = 15),
        개설일   = colDef(show = TRUE, minWidth = 10),
        설명     = colDef(minWidth = 80),
        키워드   = colDef(show = TRUE, minWidth = 50),
        토픽범주 = colDef(show = TRUE, minWidth = 30)),
      bordered = TRUE,
      highlight = TRUE    
  )
  

```

## Row {height=50%}

### Column

```{r}
#| title: 표

channels_stat |> 
  select(정당명   = party_name, 
         구독자수 = subscriber_count, 
         조회수 = view_count,
         비디오수 = video_count,
         개설일   = published_at) |> 
  mutate(정당명 = factor(정당명, 
     levels = c("민주당", "국민의힘", "조국혁신당", 
                "개혁신당", "진보당", "새로운미래",
                "기본소득당", "사회민주당"))) |> 
  mutate(개설일 = as.Date(개설일)) |>
  arrange(정당명) |> 
  mutate(
    활동기간_년 = as.numeric(interval(개설일, Sys.Date()), "years") |> round(digits = 1)) |> 
  select(정당명, 구독자수, 조회수, 비디오수, 개설일, 활동기간_년) |> 
  reactable(
      searchable = TRUE,
      defaultColDef = colDef(
        header = function(value) gsub(".", " ", value, fixed = TRUE),
        align = "center",
        minWidth = 30,
        headerStyle = list(background = "#f7f7f8")
      ),
      columns = list(
        정당명 = colDef(minWidth = 20),
        개설일 = colDef(show = TRUE),
        활동기간_년 = colDef(show = TRUE),
        구독자수   = colDef(format = colFormat(separators = TRUE,  digits = 0)),
        조회수 = colDef(format = colFormat(separators = TRUE,  digits = 0)),
        비디오수 = colDef(format = colFormat(separators = TRUE,  digits = 0))
      ),
      bordered = TRUE,
      highlight = TRUE    
  )

```

### Column

```{r}
#| title: 그래프

# Assuming channels_stat is your dataset already loaded and processed.
channels_stat %>%
  select(정당명 = party_name, 
         구독자수 = subscriber_count, 
         조회수 = view_count,
         비디오수 = video_count) %>%
  mutate(정당명 = factor(정당명, levels = c("민주당", "국민의힘", "조국혁신당", 
                                         "개혁신당", "진보당", "새로운미래",
                                         "기본소득당", "사회민주당"))) %>%
  pivot_longer(cols = c(구독자수, 조회수, 비디오수), 
               names_to = "지표", 
               values_to = "값") %>%
  mutate(값 = as.numeric(값) / 10000) %>%  # Convert values to thousands
  ggplot(aes(x = fct_reorder(정당명, 값), y = 값, fill = 정당명)) +
    geom_col(width = 0.3) +
    facet_wrap(~지표, scales = "free") +
    coord_flip() +
    theme_minimal() +
    theme(legend.position = "none",
          axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
    scale_y_continuous(labels = function(x) paste0(scales::comma(x), " 만")) +  # Custom label for thousands
    scale_fill_manual(values = c(
      "민주당" = "#152484",     # Blue
      "국민의힘" = "#E61E2B",   # Red
      "조국혁신당" = "#004098", # Green
      "개혁신당" = "#FF7210",   # Yellow
      "진보당" = "#D6001C",     # Magenta
      "새로운미래" = "#45BABD", # Cyan
      "기본소득당" = "#00D2C3", # Orange
      "사회민주당" = "#43A213"  # Grey
    )) +
    labs(title = "정당별 유튜브 활동성 지표",
         x = NULL,
         y = NULL)
```





